#ifndef QTTEMPLATEINTERPRETEREDITORVERSION_H
#define QTTEMPLATEINTERPRETEREDITORVERSION_H

#define QT_TEMPLATE_INTERPRETER_EDITOR_VERSION_STR "1.1.0"
/*
   QT_TEMPLATE_INTERPRETER_EDITOR_VERSION is (major << 16) + (minor << 8) + patch.
*/
#define QT_TEMPLATE_INTERPRETER_EDITOR_VERSION 0x010100

#endif // QTTEMPLATEINTERPRETEREDITORVERSION_H
